//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferMe.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int id { get; set; }
        public int LocationID { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public bool Active { get; set; }
    }
}
