//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferMe.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Referral = new HashSet<Referral>();
        }
    
        public int id { get; set; }
        public int PostID { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public int MinExp { get; set; }
        public int MaxExp { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public string ContactNumber { get; set; }
        public bool Active { get; set; }
        public int PostedBy { get; set; }
        public System.DateTime PostedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Referral> Referral { get; set; }
    }
}
