//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferMe.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.UserPostMapping = new HashSet<UserPostMapping>();
        }
    
        public int id { get; set; }
        public int PostID { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public int MinExp { get; set; }
        public int MaxExp { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string ContactNumber { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<UserPostMapping> UserPostMapping { get; set; }
    }
}
