//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferMe.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral
    {
        public int id { get; set; }
        public int ReferralID { get; set; }
        public int PostID { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual Post Post { get; set; }
    }
}
